project_id = "ajwtxlsadnbewjkejbut"

[functions.fetch-nevada-news]
verify_jwt = false

[functions.analyze-article]
verify_jwt = false

[functions.fetch-podcasts]
verify_jwt = false

[functions.fetch-youtube]
verify_jwt = false

[functions.fetch-social-media]
verify_jwt = false

[functions.fetch-bills]
verify_jwt = false

[functions.summarize-bill]
verify_jwt = false

[functions.send-alert-email]
verify_jwt = false
